---

- name: rocketchat
  hosts: rocketchat
  become_method: sudo
  become: yes
  gather_facts: True
  roles:
    - packages
    - users
    - ssh
    - fail2ban
    - unattended-upgrades
    - ufw
    - tor
    - {role: rocket_chat, tags: rocket_chat}
    - letsencrypt
