---

# Caution: This role is incomplete and possibly destructive. It's probably a
# bad idea to run it on a production machine in its current form. Before
# attempting to run this role, you should probably make a backup of the MySQL
# database and/or take a snapshot of the machine.

# https://www.rosehosting.com/blog/how-to-install-lemp-and-run-drupal-on-ubuntu-16-04/

- name: Install system dependencies
  apt: name="{{ item }}"
  with_items:
    - build-essential
    - drupal7
    - drush
    - git
    - letsencrypt
    - libmysqlclient-dev
    - mysql-server
    - php
    - php-console-table
    - php-curl
    - php-gd
    - php-fpm
    - php-mysql
    - php-ssh2
    - php-zip
    - python-pip
  tags: ['civicrm']

- name: Install mysql python package
  pip: name=MySQL-python state=latest
  tags: ['civicrm']

- name: Create civicrm database
  mysql_db: name="{{ civicrm_db_name }}"
  tags: ['civicrm']

- name: Create civicrm database user
  mysql_user: >
    name="{{ civicrm_db_user }}"
    password="{{ civicrm_db_password }}"
    priv="{{ civicrm_db_name }}.*:ALL"
  tags: ['civicrm']

- name: Create web root
  file: path="{{ civicrm_www_dir }}" state=directory
  tags: ['civicrm']

# - include: drupal.yml
- include: wordpress.yml

- name: Copy mysql backup script
  template: src=mysql-backup.sh dest=/usr/local/bin/mysql-backup.sh owner=root group=root mode=0700
  tags: ['civicrm', 'civicrm:backups']

- name: Create cron job for MySQL backups
  cron: >
    name="Backup MySQL"
    job="/usr/local/bin/mysql-backup.sh"
    cron_file=backup_mysql
    minute="0"
    hour="*/6"
    user=root
  tags: ['civicrm', 'civicrm:backups']
