---

# https://www.rosehosting.com/blog/how-to-install-lemp-and-run-drupal-on-ubuntu-16-04/

- name: Install system dependencies
  apt: name="{{ item }}"
  with_items:
    - build-essential
    - drupal7
    - drush
    - git
    - letsencrypt
    - libmysqlclient-dev
    - mysql-server
    - php
    - php-console-table
    - php-curl
    - php-gd
    - php-fpm
    - php-mysql
    - php-ssh2
    - php-zip
    - python-pip
  tags: ['civicrm']

- name: Install mysql python package
  pip: name=MySQL-python state=latest
  tags: ['civicrm']

- name: Create drupal database
  mysql_db: name="{{ civicrm_drupal_db_name }}"
  tags: ['civicrm']

- name: Create drupal database user
  mysql_user: >
    name="{{ civicrm_drupal_db_user }}"
    password="{{ civicrm_drupal_db_password }}"
    priv="{{ civicrm_drupal_db_name }}.*:ALL"
  tags: ['civicrm']

- name: Create civicrm database
  mysql_db: name="{{ civicrm_db_name }}"
  tags: ['civicrm']

- name: Create civicrm database user
  mysql_user: >
    name="{{ civicrm_db_user }}"
    password="{{ civicrm_db_password }}"
    priv="{{ civicrm_db_name }}.*:ALL"
  tags: ['civicrm']

- name: Create web root
  file: path="{{ civicrm_www_dir }}" state=directory
  tags: ['civicrm']

- name: Install drupal
  shell: >
    drush dl drupal --drupal-project-rename="{{ civicrm_drupal_project_name }}"
    chdir="{{ civicrm_www_dir }}"
    creates="{{ civicrm_www_dir }}/{{ civicrm_drupal_project_name }}"
  tags: ['civicrm', 'civicrm:drupal']

- name: Configure drupal
  shell: >
    drush site-install standard -y
    --db-url="mysql://{{ civicrm_drupal_db_user }}:{{ civicrm_drupal_db_password }}@localhost/{{ civicrm_drupal_db_name }}"
    --site-name="{{ civicrm_drupal_project_name }}"
    --account-name="{{ civicrm_drupal_user }}"
    --account-pass="{{ civicrm_drupal_password }}"
    chdir="{{ civicrm_www_dir }}/{{ civicrm_drupal_project_name }}"
    creates="{{ civicrm_www_dir }}/{{ civicrm_drupal_project_name }}/sites/default/settings.php"
  tags: ['civicrm', 'civicrm:drupal']

- name: Download civicrm
  get_url: >
    url="{{ civicrm_module_url }}"
    dest="{{ civicrm_www_dir }}/{{ civicrm_drupal_project_name }}/sites/all/modules/civicrm.tar.gz"
  tags: ['civicrm']

- name: Download civicrm drush file
  get_url: >
    url="{{ civicrm_drush_url }}"
    dest="~/.drush/civicrm.drush.inc"
  tags: ['civicrm']

- name: Clear drush cache
  shell: drush cache-clear drush
  tags: ['civicrm']

- name: Set permissions on drupal installation
  file: >
    path="{{ civicrm_www_dir }}/{{ civicrm_drupal_project_name }}"
    recurse=yes
    owner="www-data"
    group="www-data"
  tags: ['civicrm', 'civicrm:drupal']

- name: Install civicrm
  shell: >
    drush civicrm-install --dbuser="{{ civicrm_db_user }}" --dbpass="{{ civicrm_db_password }}"
    --dbhost="{{ civicrm_db_host }}" --dbname="{{ civicrm_db_name }}"
    --site_url="{{ civicrm_site_url }}" --destination=sites/all/modules
    chdir="{{ civicrm_www_dir }}/{{ civicrm_drupal_project_name }}"
    creates="{{ civicrm_www_dir }}/{{ civicrm_drupal_project_name }}/sites/all/modules/civicrm"
  tags: ['civicrm']
